__title__ = 'compiledb'
__description__ = 'Tool for generating Clang JSON Compilation Database files for make-based build systems.'
__url__ = 'https://github.com/nickdiego/compiledb-generator'
__version__ = '0.9.1'
__author__ = 'Nick Yamane'
__author_email__ = 'nick@diegoyam.com'
__license__ = 'GPLv3'
__copyright__ = 'Copyright 2017 Nick Yamane'
